name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build Decentralised Art Server"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Download and extract artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.event.workflow_run.id }}
        ARTIFACT_NAME: decentralised-art-server
      run: |
        mkdir -p artifact
        echo "Getting artifact list..."
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
             "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts" \
          > artifacts.json

        ARTIFACT_ID=$(jq -r --arg NAME "$ARTIFACT_NAME" '.artifacts[] | select(.name == $NAME) | .id' artifacts.json)

        if [ -z "$ARTIFACT_ID" ]; then
          echo "❌ Artifact '$ARTIFACT_NAME' not found"
          exit 1
        fi

        echo "✅ Found artifact ID: $ARTIFACT_ID"
        echo "Downloading artifact..."
        curl -L -H "Authorization: token $GITHUB_TOKEN" \
          -o artifact.zip \
          "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID/zip"

        unzip artifact.zip -d artifact
        mkdir install
        tar -xzf artifact/decentralised-art-server.tar.gz -C install

    - name: Clear remote install directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 34.118.118.250
        username: hypermusic
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Clearing /home/hypermusic/decentralised-art-install..."
          mkdir -p /tmp/empty-dir
          rsync -a --delete --exclude 'storage' /tmp/empty-dir/ /home/hypermusic/decentralised-art-install/

    - name: Install tools
      run: sudo apt update && sudo apt install -y sshpass rsync

    - name: Upload to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Create temp key file and restrict permissions
        KEY_FILE=$(mktemp)
        echo "$SSH_PRIVATE_KEY" > "$KEY_FILE"
        chmod 600 "$KEY_FILE"

        # Use rsync to copy contents (not the 'install/' dir itself)
        rsync -az --delete --exclude 'storage' -e "ssh -i $KEY_FILE -o StrictHostKeyChecking=no" \
          install/ hypermusic@34.118.118.250:/home/hypermusic/decentralised-art-install

        # Clean up key file
        rm -f "$KEY_FILE"
      shell: bash

    - name: Restart server service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 34.118.118.250
        username: hypermusic
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart decentralised-art-server
